# Generated by Django 2.2.5 on 2019-09-24 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='DishOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=10)),
                ('antrean', models.IntegerField(default=0)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Chef')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('waiting_time', models.DurationField()),
                ('table', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('0', 'waiting'), ('1', 'served')], max_length=10)),
                ('created_at', models.DateTimeField()),
                ('list', models.ManyToManyField(to='ingredients.DishOrder')),
            ],
        ),
    ]
